bad_prompt: a bad quality image
batch_size: 32
config: configs/text_conditioning/06_clip_iqa_zeroshot.yaml
config_dir: runs/configs
data: /home/sergey/conditioned-iqa/data/kadid10k/labels.csv
device: cuda:5
good_prompt: a good quality image
mlflow: true
mlflow_experiment: conditioned-iqa-text
mlflow_run_name: clip-iqa-zeroshot-s0
mlflow_tracking_uri: sqlite:///mlflow.db
score_column: scaled_subjective_score
seed: 0
split: reference
weights: /home/sergey/.cache/huggingface/hub/models--openai--clip-vit-base-patch16/snapshots/57c216476eefef5ab752ec549e440a49ae4ae5f3
workers: 2
