backbone: clip-base
batch_size: 32
command: train_text_conditioned.py --config configs/text_conditioning/00_baseline_parity.yaml
  --device cuda:6 --seed 2 --mlflow-run-name tc-baseline-s2
config: configs/text_conditioning/00_baseline_parity.yaml
config_dir: runs/configs
data: /home/sergey/conditioned-iqa/data/kadid10k/labels.csv
device: cuda:6
device_used: cuda:6
epochs: 5
feature_dim: 768
fusion_dim: 256
hidden_dim: 256
limit: null
lr: 0.001
method: baseline
mlflow: true
mlflow_experiment: conditioned-iqa-text
mlflow_run_id: c278c4e6de074882bf65f31ba68ebbb2
mlflow_run_name: tc-baseline-s2
mlflow_tracking_uri: sqlite:///mlflow.db
out: null
sampler: random
score_column: scaled_subjective_score
seed: 2
split: reference
text_weights: null
train_size: 8125
trainable_parameters: 198657
validation_size: 2000
weights: /home/sergey/.cache/huggingface/hub/models--openai--clip-vit-base-patch16/snapshots/57c216476eefef5ab752ec549e440a49ae4ae5f3
workers: 2
