data: /home/sergey/conditioned-iqa/data/kadid10k/labels.csv
backbone: clip-base
weights: /home/sergey/.cache/huggingface/hub/models--openai--clip-vit-base-patch16/snapshots/57c216476eefef5ab752ec549e440a49ae4ae5f3
method: baseline
epochs: 5
batch_size: 32
lr: 0.001
hidden_dim: 256
split: reference
sampler: random
workers: 2
device: cuda:6
seed: 0
mlflow: true
mlflow_tracking_uri: sqlite:///mlflow.db
mlflow_experiment: conditioned-iqa-text
config_dir: runs/configs
google_sheet_id: 1DZQKInig5PtctN23TXEkMzrdcc1uA9aATaxT3LTXYZY
google_worksheet: Results
